In [5]:
import numpy as np
arr = np.random.seed(0)

In [6]:
arr

In [7]:
type(arr)

NoneType

In [12]:
np.random.randint(10,size = 6)

array([0, 3, 3, 7, 9, 3])

In [13]:
np.random.randint(10,size = (3,4))

array([[5, 2, 4, 7],
       [6, 8, 8, 1],
       [6, 7, 7, 8]])

In [16]:
np.random.randint(1,10,(3,4))

array([[2, 6, 9, 5],
       [4, 1, 4, 6],
       [1, 3, 4, 9]])

In [37]:
X2 = np.random.randint(10, size=(3,4))

In [22]:
x3 = np.random.randint(10,size=(4,5,6))

In [23]:
x3.ndim

3

In [24]:
x3.shape

(4, 5, 6)

In [25]:
x3.size

120

In [26]:
x3.dtype

dtype('int64')

In [27]:
type(x3.dtype)

numpy.dtype

In [28]:
x3.itemsize

8

In [30]:
x3.nbytes

960

In [36]:
x3[1][2][3]

6

In [38]:
X2

array([[3, 2, 1, 2],
       [1, 3, 4, 1],
       [1, 0, 7, 8]])

In [40]:
X2[::-1, ::-1]

array([[8, 7, 0, 1],
       [1, 4, 3, 1],
       [2, 1, 2, 3]])

In [44]:
X2[::,0]

array([3, 1, 1])