In [1]:
import numpy as np

In [11]:
np.__version__


'1.16.4'

In [27]:
arr = np.array([1,2,3,4,5])

In [28]:
type(arr)

numpy.ndarray

In [29]:
arr1 = np.array([3.14, 4, 2, 3])
type(arr1)

numpy.ndarray

In [32]:
arr2 = np.array([1, 2, 3, 4], dtype='float32')
type(arr2)

numpy.ndarray

In [33]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [34]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
np.zeros((10,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [36]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [37]:
np.arange(0, 20, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
arr3 = np.linspace(0,1,5)

In [40]:
type(arr3)

numpy.ndarray

In [41]:
type(arr3[0])

numpy.float64

In [42]:
np.random.random((3,3))

array([[0.40805569, 0.58384545, 0.80755037],
       [0.504682  , 0.77712192, 0.64798516],
       [0.43323241, 0.91694206, 0.57706297]])

In [43]:
np.random.normal(0,1,(3,3))

array([[ 0.66372771,  0.02991737,  0.39805439],
       [-0.3006671 ,  0.70539298,  1.17569816],
       [ 1.05554439, -1.29580898,  0.06454766]])

In [44]:
np.random.randint(0,100,(3,3))

array([[47, 84, 97],
       [13, 46, 52],
       [50, 10,  1]])

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.empty(3)

array([1., 1., 1.])